"""Builder for the Chapter 3 companion notebook (the derivative).

Run:
    /opt/anaconda3/bin/python nb_ch3.py
emits ch3_derivative.ipynb in this folder. Validate by executing with nbconvert.
"""
import nbbuild as nbb

TITLE = "The Slope of a Single Point"
SUBTITLE = ("How fast is something changing *right now*, when \"rate\" seems "
            "to need two moments?")
BLURB = (
    "Three live pictures of the central act of calculus: a **secant that "
    "becomes a tangent** as the step $h$ shrinks to nothing, the **derivative "
    "traced out as its own function** while a cursor sweeps the curve, and a "
    "**corner/cusp zoom** showing the one place a slope can fail to exist."
)


def build():
    cells = [
        nbb.header(3, TITLE, SUBTITLE, BLURB),
        nbb.setup_cell(),

        # ---------------------------------------------------------------
        # Widget 1 — Secant becomes tangent
        # ---------------------------------------------------------------
        nbb.md(
            "## 1. The secant becomes the tangent\n\n"
            "Here is the move that creates calculus. The slope between two "
            "points $(a,f(a))$ and $(a+h,\\,f(a+h))$ is the **secant slope** — "
            "the average rate of change over the interval:\n\n"
            "$$\\frac{f(a+h)-f(a)}{h}.$$\n\n"
            "Now slide the second point in: shrink $h$ toward $0$. The two "
            "points merge, the gray secant **pivots**, and it settles onto the "
            "red **tangent** line — the slope at the single instant $a$. Watch "
            "the live secant slope chase the true derivative $f'(a)$ as you "
            "drag $h$ small. (Try $h$ both positive and negative — the secant "
            "swings in from either side and lands on the same line.)"
        ),
        nbb.code(
            "# Each preset carries f, its hand-computed derivative f', a label,\n"
            "# and a window. Derivatives are exactly the ones earned in the\n"
            "# chapter: (x^2)'=2x, (sin x)'=cos x, (sqrt x)'=1/(2 sqrt x).\n"
            "_F1 = {\n"
            "    'x^2':\n"
            "        dict(f=lambda x: x**2, df=lambda x: 2*x,\n"
            "             tex='x^2', dtex='2a', xlim=(-3.0, 3.0)),\n"
            "    'sin(x)':\n"
            "        dict(f=np.sin, df=np.cos,\n"
            "             tex=r'\\sin x', dtex=r'\\cos a', xlim=(-1.0, 6.5)),\n"
            "    'sqrt(x)':\n"
            "        dict(f=np.sqrt, df=lambda x: 0.5/np.sqrt(x),\n"
            "             tex=r'\\sqrt{x}', dtex=r'1/(2\\sqrt{a})',\n"
            "             xlim=(0.05, 6.0)),\n"
            "}\n"
            "\n"
            "def _secant(which='x^2', a=1.0, h=1.5):\n"
            "    p = _F1[which]\n"
            "    f, df = p['f'], p['df']\n"
            "    lo, hi = p['xlim']\n"
            "    # Keep a, and a+h, inside the domain window.\n"
            "    a = float(np.clip(a, lo + 0.05, hi - 0.05))\n"
            "    if a + h < lo + 0.02:\n"
            "        h = (lo + 0.02) - a\n"
            "    if a + h > hi - 0.02:\n"
            "        h = (hi - 0.02) - a\n"
            "\n"
            "    xs = np.linspace(lo, hi, 600)\n"
            "    fa, fah = f(a), f(a + h)\n"
            "    slope_true = df(a)\n"
            "\n"
            "    fig, ax = plt.subplots()\n"
            "    ax.plot(xs, f(xs), color=BLUE, lw=2.4, label=rf'$f(x)={p[\"tex\"]}$')\n"
            "    # True tangent at a (red).\n"
            "    ax.plot(xs, fa + slope_true*(xs - a), color=RED, lw=2.0,\n"
            "            label='tangent (slope $f\\'(a)$)')\n"
            "    # Secant through the two points (gray) — only if h != 0.\n"
            "    if abs(h) > 1e-9:\n"
            "        slope_sec = (fah - fa)/h\n"
            "        ax.plot(xs, fa + slope_sec*(xs - a), color=GRAY, lw=2.0,\n"
            "                ls='--', label='secant')\n"
            "        ax.plot([a + h], [fah], 'o', color=GRAY, ms=8, zorder=5)\n"
            "    else:\n"
            "        slope_sec = slope_true\n"
            "    ax.plot([a], [fa], 'o', color=RED, ms=8, zorder=6)\n"
            "\n"
            "    ax.set_xlim(lo, hi)\n"
            "    ax.set_xlabel('$x$'); ax.set_ylabel('$y$')\n"
            "    ax.set_title('Secant pivoting onto the tangent', color=DARK)\n"
            "    ax.legend(loc='upper left', framealpha=0.9)\n"
            "    plt.show()\n"
            "\n"
            "    gap = slope_sec - slope_true\n"
            "    display(Markdown(\n"
            "        rf'secant slope $=\\dfrac{{f(a+h)-f(a)}}{{h}}'\n"
            "        rf'= {slope_sec:.4f}$ &nbsp;&nbsp; vs &nbsp;&nbsp; '\n"
            "        rf'true $f\\'(a)={p[\"dtex\"]}={slope_true:.4f}$ '\n"
            "        rf'&nbsp;&nbsp;(gap ${gap:+.4f}$)'))\n"
            "\n"
            "interact(_secant,\n"
            "         which=Dropdown(options=list(_F1), value='x^2',\n"
            "                        description='function'),\n"
            "         a=FloatSlider(value=1.0, min=-2.5, max=2.5, step=0.1,\n"
            "                       description='base $a$'),\n"
            "         h=FloatSlider(value=1.5, min=-2.0, max=2.0, step=0.05,\n"
            "                       description='step $h$'));\n"
        ),

        # ---------------------------------------------------------------
        # Widget 2 — Derivative as a function
        # ---------------------------------------------------------------
        nbb.md(
            "## 2. The derivative is itself a function\n\n"
            "The slope $f'(a)$ isn't a single number stuck to one point — it's "
            "a **rule** that returns the slope at *every* point. Watch that "
            "rule get built. Slide the cursor $x_0$ across the curve; the top "
            "panel shows $f$ with its red tangent at $x_0$, and the bottom "
            "panel plots the slope-function $f'(x)$ with a moving dot at "
            "$(x_0,\\,f'(x_0))$.\n\n"
            "As the cursor moves, the dot traces the lower curve point by "
            "point: where $f$ is steep, $f'$ is large; where $f$ is flat, $f'$ "
            "crosses zero. The bottom graph *is* the slope of the top one."
        ),
        nbb.code(
            "# f, f', and a window. f(x) = (1/3)x^3 - x has slope f'(x)=x^2-1,\n"
            "# a clean parabola that crosses zero at the two turning points.\n"
            "_F2 = {\n"
            "    '(1/3)x^3 - x':\n"
            "        dict(f=lambda x: x**3/3 - x, df=lambda x: x**2 - 1,\n"
            "             tex=r'\\frac{1}{3}x^3 - x', dtex='x^2-1',\n"
            "             xlim=(-2.4, 2.4)),\n"
            "    'sin(x)':\n"
            "        dict(f=np.sin, df=np.cos,\n"
            "             tex=r'\\sin x', dtex=r'\\cos x', xlim=(-0.5, 6.8)),\n"
            "    'x^2':\n"
            "        dict(f=lambda x: x**2, df=lambda x: 2*x,\n"
            "             tex='x^2', dtex='2x', xlim=(-3.0, 3.0)),\n"
            "}\n"
            "\n"
            "def _slopefn(which='(1/3)x^3 - x', x0=0.6):\n"
            "    p = _F2[which]\n"
            "    f, df = p['f'], p['df']\n"
            "    lo, hi = p['xlim']\n"
            "    x0 = float(np.clip(x0, lo, hi))\n"
            "    xs = np.linspace(lo, hi, 600)\n"
            "    m = df(x0)\n"
            "\n"
            "    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7.2, 6.4),\n"
            "                                   sharex=True)\n"
            "    # Top: f with the tangent at x0.\n"
            "    ax1.plot(xs, f(xs), color=BLUE, lw=2.4, label=rf'$f={p[\"tex\"]}$')\n"
            "    tx = np.linspace(x0 - 0.9, x0 + 0.9, 2)\n"
            "    ax1.plot(tx, f(x0) + m*(tx - x0), color=RED, lw=2.2,\n"
            "             label='tangent at $x_0$')\n"
            "    ax1.plot([x0], [f(x0)], 'o', color=RED, ms=8, zorder=5)\n"
            "    ax1.axvline(x0, color=GRAY, lw=0.8, ls=':')\n"
            "    ax1.set_ylabel('$f(x)$')\n"
            "    ax1.set_title('Top: the function and its tangent', color=DARK)\n"
            "    ax1.legend(loc='upper left', framealpha=0.9)\n"
            "    # Bottom: f' with the moving dot.\n"
            "    ax2.plot(xs, df(xs), color=RED, lw=2.4,\n"
            "             label=rf\"$f'(x)={p['dtex']}$\")\n"
            "    ax2.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax2.axvline(x0, color=GRAY, lw=0.8, ls=':')\n"
            "    ax2.plot([x0], [m], 'o', color=RED, ms=9, zorder=5)\n"
            "    ax2.annotate(rf'$f\\'(x_0)={m:.2f}$', xy=(x0, m),\n"
            "                 xytext=(8, 8), textcoords='offset points',\n"
            "                 color=RED, fontsize=11)\n"
            "    ax2.set_xlabel('$x$'); ax2.set_ylabel(\"$f'(x)$\")\n"
            "    ax2.set_title('Bottom: the slope traced as a function',\n"
            "                  color=DARK)\n"
            "    ax2.legend(loc='upper left', framealpha=0.9)\n"
            "    ax2.set_xlim(lo, hi)\n"
            "    plt.tight_layout()\n"
            "    plt.show()\n"
            "\n"
            "interact(_slopefn,\n"
            "         which=Dropdown(options=list(_F2), value='(1/3)x^3 - x',\n"
            "                        description='function'),\n"
            "         x0=FloatSlider(value=0.6, min=-2.3, max=2.3, step=0.05,\n"
            "                        description='cursor $x_0$'));\n"
        ),

        # ---------------------------------------------------------------
        # Widget 3 — Corner / cusp explorer
        # ---------------------------------------------------------------
        nbb.md(
            "## 3. Where the slope fails: corners and cusps\n\n"
            "A derivative is a *limit*, and limits don't always exist — so "
            "neither do derivatives. Zoom in on $x=0$ for two continuous "
            "functions that both refuse a slope there, but for different "
            "reasons.\n\n"
            "- **$|x|$** keeps a sharp **corner** at every zoom — it never "
            "straightens out. Its difference quotient $\\dfrac{|h|}{h}$ is "
            "$+1$ from the right and $-1$ from the left: the two one-sided "
            "limits disagree, so $f'(0)$ does not exist. (This is exactly the "
            "$\\tfrac{|x|}{x}$ jump from Chapter 2, reappearing as a slope.)\n"
            "- **$x^{1/3}$** is smooth but develops a **vertical tangent**: "
            "as you zoom, it stands straight up, so the slope runs off to "
            "$+\\infty$.\n\n"
            "Drag the **zoom** slider (a log scale): the smaller the window, "
            "the closer you look at the origin."
        ),
        nbb.code(
            "def _cbrt(x):\n"
            "    # Real cube root, valid for negative x (np.cbrt is real-valued).\n"
            "    return np.cbrt(x)\n"
            "\n"
            "_F3 = {\n"
            "    '|x|  (corner)':\n"
            "        dict(f=np.abs, tex='|x|', kind='corner'),\n"
            "    'x^(1/3)  (cusp / vertical tangent)':\n"
            "        dict(f=_cbrt, tex='x^{1/3}', kind='cusp'),\n"
            "}\n"
            "\n"
            "def _corner(which='|x|  (corner)', zoom=1.0, show_quotient=True):\n"
            "    p = _F3[which]\n"
            "    f = p['f']\n"
            "    w = float(zoom)                 # half-width of the window\n"
            "    xs = np.linspace(-w, w, 601)\n"
            "    fig, ax = plt.subplots()\n"
            "    ax.plot(xs, f(xs), color=BLUE, lw=2.6, label=rf'$f(x)={p[\"tex\"]}$')\n"
            "    ax.axvline(0, color=GRAY, lw=0.8)\n"
            "    ax.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax.plot([0], [f(0.0)], 'o', color=RED, ms=8, zorder=5)\n"
            "    ax.set_xlim(-w, w)\n"
            "    ax.set_xlabel('$x$'); ax.set_ylabel('$y$')\n"
            "    note = ('corner stays sharp' if p['kind'] == 'corner'\n"
            "            else 'curve stands vertical')\n"
            "    ax.set_title(f'zoom half-width = {w:.3g}   ({note})',\n"
            "                 color=DARK)\n"
            "    ax.legend(loc='upper left', framealpha=0.9)\n"
            "    plt.show()\n"
            "\n"
            "    if p['kind'] == 'corner' and show_quotient:\n"
            "        hpos, hneg = w/2, -w/2\n"
            "        qpos = (abs(hpos) - 0.0)/hpos\n"
            "        qneg = (abs(hneg) - 0.0)/hneg\n"
            "        display(Markdown(\n"
            "            rf'difference quotient $\\dfrac{{|h|}}{{h}}$ at $a=0$: '\n"
            "            rf'right ($h>0$) $={qpos:+.0f}$, &nbsp; '\n"
            "            rf'left ($h<0$) $={qneg:+.0f}$ — they disagree, so '\n"
            "            rf'$f\\'(0)$ does **not** exist.'))\n"
            "    elif p['kind'] == 'cusp':\n"
            "        hsmall = w/2\n"
            "        slope = (_cbrt(hsmall) - 0.0)/hsmall\n"
            "        display(Markdown(\n"
            "            rf'secant slope across $[0,\\,{hsmall:.3g}]$ is '\n"
            "            rf'$\\approx {slope:.2f}$ — it grows without bound as '\n"
            "            rf'you zoom in: a **vertical tangent**, slope $\\to'\n"
            "            rf'+\\infty$.'))\n"
            "\n"
            "interact(_corner,\n"
            "         which=Dropdown(options=list(_F3), value='|x|  (corner)',\n"
            "                        description='function'),\n"
            "         zoom=FloatLogSlider(value=1.0, base=10, min=-3, max=0.3,\n"
            "                             step=0.1, description='zoom'),\n"
            "         show_quotient=Checkbox(value=True,\n"
            "                                description='show |h|/h'));\n"
        ),

        nbb.md(
            "---\n\n"
            "*One limit — the slope of a single point — and the rest of the "
            "book is its consequences. Next, **Chapter 4** proves a handful of "
            "rules so you never have to expand $(a+h)^n$ by hand again; and the "
            "one-sided quotients you just watched fail at the corner of $|x|$ "
            "return as Fermat's lemma in Chapter 6.*"
        ),
    ]
    nbb.build("ch3_derivative.ipynb", cells)


if __name__ == "__main__":
    build()
