"""Builder for the Chapter 1 companion notebook (sequences & limits).

    cd notebooks && python3 nb_ch1.py

Emits notebooks/ch1_sequences.ipynb. The notebook is self-contained: its first
cell (nbb.setup_cell()) imports numpy/matplotlib/ipywidgets/IPython and the
Book 2 palette, so the widget cells below assume np, plt, animation, the
ipywidgets factories, HTML/display/Markdown, the colour constants, and axes().
"""
import nbbuild as nbb

TITLE = "Patterns That Go Somewhere"
SUBTITLE = "What does a list of numbers want to become?"
BLURB = (
    "Three live experiments on the central idea of the chapter — that a "
    "never-ending list can be *sneaking up on* a single number. You will play "
    "the $\\varepsilon$–$N$ game against a shrinking tolerance, watch a "
    "race between a base and an exponent decide a $1^\\infty$ limit, and climb "
    "a cobweb staircase to a fixed point you cannot write in closed form."
)


def build():
    cells = [
        nbb.header(1, TITLE, SUBTITLE, BLURB),
        nbb.setup_cell(),

        # ---- Widget 1: epsilon-N game -------------------------------------
        nbb.md(
            "## 1. Name your tolerance — the $\\varepsilon$–$N$ game\n\n"
            "Here is the definition turned into a game. A skeptic names a "
            "tolerance $\\varepsilon>0$ and bets your terms cannot get within "
            "$\\varepsilon$ of the limit $L$ *and stay there*. You answer with "
            "a **cutoff** $N$: a seat number past which **every** term is "
            "inside the window $L\\pm\\varepsilon$. If you can win for any "
            "$\\varepsilon$ the skeptic dares to name, then $a_n\\to L$.\n\n"
            "Pick a sequence and drag $\\varepsilon$. The shaded band is "
            "$L\\pm\\varepsilon$; terms still *outside* it are grey, terms from "
            "the cutoff $N$ onward are green. Watch what happens as you shrink "
            "$\\varepsilon$ toward zero: the band pinches, and the cutoff $N$ "
            "marches to the right. That trade-off *is* the limit."
        ),
        nbb.code(
            "# The convergent sequences on offer, each with its true limit L.\n"
            "_SEQS = {\n"
            "    'a_n = 1/n  ->  0':            (lambda n: 1.0 / n,            0.0),\n"
            "    'a_n = n/(n+1)  ->  1':        (lambda n: n / (n + 1.0),      1.0),\n"
            "    'a_n = (-1)^n / n  ->  0':     (lambda n: (-1.0) ** n / n,    0.0),\n"
            "    'a_n = (1/2)^n  ->  0':        (lambda n: 0.5 ** n,           0.0),\n"
            "}\n"
            "_NTERMS = 40\n"
            "\n"
            "def _epsilon_N(seq='a_n = 1/n  ->  0', eps=0.2):\n"
            "    rule, L = _SEQS[seq]\n"
            "    n = np.arange(1, _NTERMS + 1)\n"
            "    a = rule(n)\n"
            "    inside = np.abs(a - L) < eps          # term is within the window\n"
            "    # Cutoff N = smallest index past which ALL later terms stay inside.\n"
            "    # Scan from the right: the last term that is still OUTSIDE fixes N.\n"
            "    outside_idx = np.where(~inside)[0]\n"
            "    N = int(n[outside_idx[-1]]) if outside_idx.size else 0\n"
            "    past = n > N                          # the green tail\n"
            "\n"
            "    fig, ax = plt.subplots()\n"
            "    axes(ax, f'{seq}    (tolerance \\u03b5 = {eps:.4g})')\n"
            "    ax.axhline(L, color=DARK, lw=1.3, zorder=1)\n"
            "    ax.axhspan(L - eps, L + eps, color=SHADE, alpha=0.45, zorder=0,\n"
            "               label=f'window  L \\u00b1 \\u03b5')\n"
            "    ax.scatter(n[~past], a[~past], s=34, color=GRAY, zorder=3,\n"
            "               label='before cutoff')\n"
            "    ax.scatter(n[past], a[past], s=34, color=GREEN, zorder=3,\n"
            "               label='from N onward (all inside)')\n"
            "    ax.axvline(N + 0.5, color=RED, lw=1.6, ls='--', zorder=2)\n"
            "    ax.annotate(f'N = {N}', xy=(N + 0.5, L), xytext=(N + 2.5, L + 1.4 * eps),\n"
            "                color=RED, fontsize=13,\n"
            "                arrowprops=dict(arrowstyle='->', color=RED))\n"
            "    ax.set_xlabel('n  (seat number)'); ax.set_ylabel('a_n')\n"
            "    ax.set_xlim(0, _NTERMS + 1)\n"
            "    pad = max(eps * 1.6, 0.05)\n"
            "    lo = min(a.min(), L - eps) - pad\n"
            "    hi = max(a.max(), L + eps) + pad\n"
            "    ax.set_ylim(lo, hi)\n"
            "    ax.legend(loc='upper right', framealpha=0.9, fontsize=9)\n"
            "    plt.show()\n"
            "\n"
            "interact(_epsilon_N,\n"
            "         seq=Dropdown(options=list(_SEQS), value='a_n = 1/n  ->  0',\n"
            "                      description='sequence'),\n"
            "         eps=FloatLogSlider(value=0.2, base=10, min=-3, max=0, step=0.05,\n"
            "                            description='\\u03b5', readout_format='.4g'));"
        ),

        # ---- Widget 2: the 1^inf race -------------------------------------
        nbb.md(
            "## 2. A race for $1^\\infty$ — where does $\\left(1+\\tfrac{b}{n}\\right)^{pn}$ land?\n\n"
            "The form $1^\\infty$ is indeterminate because the answer hinges on "
            "a *race*: how fast the base $1+\\tfrac{b}{n}$ sinks toward $1$ "
            "against how fast the exponent $pn$ climbs. The gauge that settles "
            "it: look at $(\\text{exponent})\\times(\\text{base}-1)$. Here that "
            "is $pn\\cdot\\tfrac{b}{n}=b\\,p$, a constant — so the sequence "
            "lands on\n\n"
            "$$\\left(1+\\frac{b}{n}\\right)^{pn}\\longrightarrow e^{\\,b\\,p}.$$\n\n"
            "Drag the base-rate $b$ and the power $p$. The blue dots are the "
            "sequence; the red line is the predicted limit $e^{bp}$. Push the "
            "product $bp$ toward $0$ and the limit slides to $1$; crank it up "
            "and the limit shoots toward $\\infty$. Set $b=p=1$ to recover the "
            "birth of $e$ itself."
        ),
        nbb.code(
            "def _race(b=1.0, p=1.0):\n"
            "    n = np.arange(1, 121)\n"
            "    a = (1.0 + b / n) ** (p * n)\n"
            "    k = b * p                       # the gauge:  (exponent)x(base-1)\n"
            "    limit = np.exp(k)\n"
            "\n"
            "    fig, ax = plt.subplots()\n"
            "    axes(ax, f'(1 + {b:.2g}/n)^({p:.2g}\\u00b7n)   \\u2192   e^(b\\u00b7p) = e^{{{k:.3g}}}')\n"
            "    ax.scatter(n, a, s=20, color=BLUE, zorder=3, label='the sequence')\n"
            "    ax.axhline(limit, color=RED, lw=2.0, ls='--', zorder=2,\n"
            "               label=f'limit  e^(bp) = {limit:.5g}')\n"
            "    ax.axhline(1.0, color=GRAY, lw=1.0, ls=':', zorder=1, label='y = 1')\n"
            "    ax.set_xlabel('n'); ax.set_ylabel('a_n')\n"
            "    lo = min(1.0, a.min(), limit); hi = max(a.max(), limit)\n"
            "    span = hi - lo or 1.0\n"
            "    ax.set_ylim(lo - 0.08 * span, hi + 0.12 * span)\n"
            "    ax.legend(loc='best', framealpha=0.9, fontsize=9)\n"
            "    # A one-line read-out of which way the race tipped.\n"
            "    if abs(k) < 0.05:\n"
            "        verdict = 'b\\u00b7p \\u2248 0: the base wins, limit swings toward 1.'\n"
            "    elif k > 0:\n"
            "        verdict = f'b\\u00b7p = {k:.3g} > 0: balanced, limit = e^{k:.3g} = {limit:.4g}.'\n"
            "    else:\n"
            "        verdict = f'b\\u00b7p = {k:.3g} < 0: limit = e^{k:.3g} = {limit:.4g} (below 1).'\n"
            "    ax.text(0.5, -0.22, verdict, transform=ax.transAxes, ha='center',\n"
            "            color=DARK, fontsize=10)\n"
            "    plt.show()\n"
            "\n"
            "interact(_race,\n"
            "         b=FloatSlider(value=1.0, min=-2.0, max=3.0, step=0.1,\n"
            "                       description='base-rate b'),\n"
            "         p=FloatSlider(value=1.0, min=0.2, max=4.0, step=0.1,\n"
            "                       description='power p'));"
        ),

        # ---- Widget 3: cobweb to a fixed point ----------------------------
        nbb.md(
            "## 3. Climbing to a fixed point — the cobweb for $a_{n+1}=\\sqrt{2+a_n}$\n\n"
            "Some sequences have no closed form, yet still settle on an exact "
            "limit. Take $a_1=\\sqrt{2}$ and $a_{n+1}=\\sqrt{2+a_n}$. It climbs: "
            "$\\sqrt2,\\ \\sqrt{2+\\sqrt2},\\ \\ldots$, bounded above by $2$. If "
            "it converges to $L$, then $L$ must satisfy its own rule, "
            "$L=\\sqrt{2+L}$, which gives $L=2$ — a **fixed point**, a value the "
            "process leaves unchanged.\n\n"
            "The **cobweb** makes this visible. The blue curve is "
            "$y=\\sqrt{2+x}$; the grey line is $y=x$. From a term on the "
            "diagonal, go *up* to the curve (that computes the next term), then "
            "*across* to the diagonal (that copies it back onto the input "
            "axis), and repeat. Drag the number of steps and watch the "
            "staircase spiral into the corner at $(2,2)$ where the two graphs "
            "cross. The dots on the right are the same terms, marching to $2$."
        ),
        nbb.code(
            "def _g(x):\n"
            "    return np.sqrt(2.0 + x)\n"
            "\n"
            "def _cobweb(steps=6):\n"
            "    # Build the orbit a_1 = sqrt(2), a_{n+1} = sqrt(2 + a_n).\n"
            "    a = [np.sqrt(2.0)]\n"
            "    for _ in range(steps):\n"
            "        a.append(_g(a[-1]))\n"
            "    a = np.array(a)\n"
            "\n"
            "    fig, (axL, axR) = plt.subplots(1, 2, figsize=(10.4, 4.6))\n"
            "\n"
            "    # --- left: the cobweb diagram ---\n"
            "    axes(axL, 'cobweb:  y = \\u221a(2 + x)  vs  y = x')\n"
            "    xs = np.linspace(0, 2.6, 400)\n"
            "    axL.plot(xs, _g(xs), color=BLUE, label='y = \\u221a(2 + x)')\n"
            "    axL.plot(xs, xs, color=GRAY, lw=1.4, ls='--', label='y = x')\n"
            "    axL.plot(2, 2, 'o', color=RED, ms=8, zorder=5)\n"
            "    axL.annotate('fixed point (2, 2)', xy=(2, 2), xytext=(0.9, 2.35),\n"
            "                 color=RED, fontsize=10,\n"
            "                 arrowprops=dict(arrowstyle='->', color=RED))\n"
            "    # staircase: (x, x) -> (x, g(x)) -> (g(x), g(x)) -> ...\n"
            "    x = a[0]\n"
            "    axL.plot([x, x], [0, _g(x)], color=GREEN, lw=1.4, zorder=4)\n"
            "    for i in range(steps):\n"
            "        y = _g(x)\n"
            "        axL.plot([x, y], [y, y], color=GREEN, lw=1.4, zorder=4)   # across to y=x\n"
            "        axL.plot([y, y], [y, _g(y)], color=GREEN, lw=1.4, zorder=4)  # up to curve\n"
            "        x = y\n"
            "    axL.set_xlabel('x = a_n'); axL.set_ylabel('a_{n+1}')\n"
            "    axL.set_xlim(0, 2.6); axL.set_ylim(0, 2.6)\n"
            "    axL.legend(loc='lower right', framealpha=0.9, fontsize=9)\n"
            "\n"
            "    # --- right: the terms approaching 2 ---\n"
            "    axes(axR, 'the terms a_n \\u2192 2')\n"
            "    idx = np.arange(1, len(a) + 1)\n"
            "    axR.axhline(2.0, color=RED, lw=1.6, ls='--', label='limit L = 2')\n"
            "    axR.plot(idx, a, '-o', color=BLUE, ms=6, zorder=3)\n"
            "    for xi, yi in zip(idx, a):\n"
            "        axR.annotate(f'{yi:.4f}', xy=(xi, yi), xytext=(0, 7),\n"
            "                     textcoords='offset points', ha='center',\n"
            "                     fontsize=8, color=DARK)\n"
            "    axR.set_xlabel('n'); axR.set_ylabel('a_n')\n"
            "    axR.set_xlim(0.5, len(a) + 0.5); axR.set_ylim(1.3, 2.08)\n"
            "    axR.legend(loc='lower right', framealpha=0.9, fontsize=9)\n"
            "    fig.tight_layout()\n"
            "    plt.show()\n"
            "\n"
            "interact(_cobweb,\n"
            "         steps=IntSlider(value=6, min=1, max=12, step=1,\n"
            "                         description='iterations'));"
        ),
    ]
    nbb.build("ch1_sequences.ipynb", cells)


if __name__ == "__main__":
    build()
