"""Builder for the Chapter 9 companion notebook (Newton's method & gradient
descent) — the centerpiece notebook of Book 2.

Run:
    /opt/anaconda3/bin/python nb_ch9.py
emits ch9_newton_gradient_descent.ipynb in this folder. Validate by executing
with nbconvert:
    /opt/anaconda3/bin/jupyter nbconvert --to notebook --execute --inplace \
        --ExecutePreprocessor.timeout=300 ch9_newton_gradient_descent.ipynb

The notebook is self-contained: its first cell (nbb.setup_cell()) imports
numpy/matplotlib/ipywidgets/IPython and the Book 2 palette, so the widget cells
below assume np, plt, animation, the ipywidgets factories, HTML/display/
Markdown, the colour constants, and axes(). Interactivity is ipywidgets
`interact` only (sliders/dropdowns/checkboxes) so it runs under nbconvert; the
spec's "draggable start" is implemented as a slider for x0.
"""
import nbbuild as nbb

TITLE = "When You Can't Solve It, Chase It"
SUBTITLE = "How to find an answer by taking smarter and smarter guesses"
BLURB = (
    "The centerpiece lab of the book, and where most of Chapter 9's practice "
    "lives. Five live experiments turn iteration into something you *watch*: a "
    "gradient-descent playground where one dial — the learning rate — slides "
    "the glide into a spiral into an explosion; Newton's method doubling its "
    "correct digits on $\\sqrt2$ and then flying apart on $x^{1/3}$; a "
    "two-valley landscape where the *starting point* alone decides which "
    "minimum you fall into; a head-to-head step count of Newton against "
    "gradient descent; and your first real optimizer — momentum — on a steep, "
    "ill-conditioned bowl."
)


def build():
    cells = [
        nbb.header(9, TITLE, SUBTITLE, BLURB),
        nbb.setup_cell(),

        # ===============================================================
        # Widget 1 — the gradient-descent playground (the four regimes)
        # ===============================================================
        nbb.md(
            "## 1. The gradient-descent playground — turn the dial, watch the regime change\n\n"
            "Here is the whole chapter in one picture. We minimize the simplest "
            "valley there is, the bowl $f(x)=x^2$, whose bottom is plainly at "
            "$x=0$. Starting from a guess $x_0$, gradient descent repeats one "
            "line:\n\n"
            "$$x_{k+1}=x_k-\\eta\\,f'(x_k)=x_k-\\eta\\,(2x_k)=(1-2\\eta)\\,x_k.$$\n\n"
            "Every step just multiplies your position by the fixed number "
            "$1-2\\eta$ — so the whole fate of the run is decided by the single "
            "quantity $|1-2\\eta|$, exactly the geometric-sequence test from "
            "Chapter 1. Drag the **start** $x_0$ (this is your 'draggable "
            "start') and, more importantly, the **learning rate** $\\eta$, and "
            "watch the path on the bowl pass through four regimes:\n\n"
            "- **smooth glide** ($\\eta$ small, factor in $(0,1)$) — creeps "
            "patiently down one side and lands;\n"
            "- **shrinking spiral** ($\\tfrac12<\\eta<1$, factor in $(-1,0)$) — "
            "overshoots the bottom each step, but the overshoots shrink, so it "
            "zig-zags in;\n"
            "- **stuck bounce** ($\\eta=1$, factor $=-1$) — ping-pongs between "
            "$\\pm x_0$ forever, never arriving;\n"
            "- **explosion** ($\\eta>1$, factor $<-1$) — each step lands farther "
            "out than the last, and it detonates.\n\n"
            "The magic value $\\eta=\\tfrac12$ makes the factor $0$: gradient "
            "descent jumps to the exact minimum in **one step**. Try it."
        ),
        nbb.code(
            "def _playground(x0=1.0, eta=0.1, n_steps=12):\n"
            "    f  = lambda x: x**2\n"
            "    fp = lambda x: 2.0 * x\n"
            "    # Run the descent x_{k+1} = x_k - eta*f'(x_k), guarding overflow.\n"
            "    xs = [float(x0)]\n"
            "    for _ in range(n_steps):\n"
            "        nxt = xs[-1] - eta * fp(xs[-1])\n"
            "        if not np.isfinite(nxt) or abs(nxt) > 1e6:\n"
            "            xs.append(nxt); break\n"
            "        xs.append(nxt)\n"
            "    xs = np.array(xs)\n"
            "    ys = f(xs)\n"
            "\n"
            "    factor = 1.0 - 2.0 * eta\n"
            "    a = abs(factor)\n"
            "    if abs(eta - 0.5) < 1e-9:\n"
            "        regime, col = 'one-step landing (\\u03b7 = \\u00bd)', GREEN\n"
            "    elif a < 1e-9:\n"
            "        regime, col = 'one-step landing', GREEN\n"
            "    elif factor > 0 and a < 1:\n"
            "        regime, col = 'smooth glide  \\u2713', GREEN\n"
            "    elif factor < 0 and a < 1:\n"
            "        regime, col = 'shrinking spiral  \\u2713', ORANGE\n"
            "    elif a == 1 or abs(a - 1) < 1e-9:\n"
            "        regime, col = 'stuck bounce  \\u2717', RED\n"
            "    else:\n"
            "        regime, col = 'explosion  \\u2717', RED\n"
            "\n"
            "    fig, (axL, axR) = plt.subplots(1, 2, figsize=(11.0, 4.6))\n"
            "\n"
            "    # --- left: the path on the bowl ---\n"
            "    span = max(abs(x0) * 1.3, np.nanmax(np.abs(xs[np.isfinite(xs)])) * 1.05, 1.0)\n"
            "    span = min(span, 6.0)\n"
            "    gx = np.linspace(-span, span, 400)\n"
            "    axes(axL, 'descent path on the bowl  f(x) = x\\u00b2')\n"
            "    axL.plot(gx, f(gx), color=BLUE, lw=2.4, zorder=1, label='f(x) = x\\u00b2')\n"
            "    vis = np.isfinite(xs) & (np.abs(xs) <= span)\n"
            "    axL.plot(xs[vis], ys[vis], '-', color=RED, lw=1.6, zorder=3)\n"
            "    axL.scatter(xs[vis], ys[vis], s=42, color=RED, zorder=4,\n"
            "                label='descent steps')\n"
            "    axL.scatter([x0], [f(x0)], s=95, color=DARK, zorder=5,\n"
            "                marker='s', label='start  x\\u2080')\n"
            "    # Mark the converged point green if we actually settled near 0.\n"
            "    if np.isfinite(xs[-1]) and abs(xs[-1]) < 1e-2:\n"
            "        axL.scatter([xs[-1]], [f(xs[-1])], s=150, color=GREEN,\n"
            "                    zorder=6, marker='*', label='converged \\u2192 0')\n"
            "    axL.set_xlabel('x'); axL.set_ylabel('f(x)')\n"
            "    axL.set_xlim(-span, span); axL.set_ylim(-0.05 * span**2, span**2)\n"
            "    axL.legend(loc='upper center', framealpha=0.9, fontsize=9)\n"
            "\n"
            "    # --- right: x_k versus step number ---\n"
            "    axes(axR, f'regime:  {regime}')\n"
            "    k = np.arange(len(xs))\n"
            "    axR.axhline(0.0, color=GRAY, lw=1.0, ls=':')\n"
            "    kk = k[vis]; xx = xs[vis]\n"
            "    axR.plot(kk, xx, '-o', color=col, ms=6, zorder=3)\n"
            "    axR.set_xlabel('step k'); axR.set_ylabel('x_k')\n"
            "    axR.set_title(f'regime:  {regime}', color=col)\n"
            "    axR.text(0.5, 1.12, f'factor 1\\u22122\\u03b7 = {factor:+.3f}'\n"
            "             f'   (|1\\u22122\\u03b7| = {a:.3f})',\n"
            "             transform=axR.transAxes, ha='center', color=DARK,\n"
            "             fontsize=11)\n"
            "    if np.all(np.isfinite(xs)):\n"
            "        ylo, yhi = np.min(xs), np.max(xs)\n"
            "        pad = max(0.1, 0.12 * (yhi - ylo))\n"
            "        axR.set_ylim(ylo - pad, yhi + pad)\n"
            "    fig.tight_layout()\n"
            "    plt.show()\n"
            "\n"
            "    # A short numeric read-out of the first several step values.\n"
            "    shown = ', '.join(f'{v:.4g}' for v in xs[:7])\n"
            "    tail = ' \\u2026' if len(xs) > 7 else ''\n"
            "    display(Markdown(f'**Steps:** $x_0,\\\\,x_1,\\\\,\\\\ldots$ = '\n"
            "                     f'`{shown}{tail}`'))\n"
            "\n"
            "interact(_playground,\n"
            "         x0=FloatSlider(value=1.0, min=-3.0, max=3.0, step=0.1,\n"
            "                        description='start x\\u2080'),\n"
            "         eta=FloatSlider(value=0.1, min=0.01, max=1.2, step=0.01,\n"
            "                         description='\\u03b7 (rate)', readout_format='.2f'),\n"
            "         n_steps=IntSlider(value=12, min=2, max=30, step=1,\n"
            "                           description='steps'));"
        ),

        # ===============================================================
        # Widget 2 — Newton's method: digit-doubling, and the blow-up
        # ===============================================================
        nbb.md(
            "## 2. Newton's method — fast when it works, spectacular when it doesn't\n\n"
            "Newton's method replaces the hard curve with its easy tangent line "
            "and jumps to where the *line* hits zero:\n\n"
            "$$x_{n+1}=x_n-\\frac{f(x_n)}{f'(x_n)}.$$\n\n"
            "Pick **$g(x)=x^2-2$** (its root is $\\sqrt2$) and watch the "
            "*correct digits roughly double every step* — $2,5,11,\\ldots$ — "
            "from a sloppy start. That blistering speed is **quadratic "
            "convergence**, Newton's signature. Then switch to **$x^{1/3}$**, "
            "whose only root is $0$: its rule simplifies to $x_{n+1}=-2x_n$, so "
            "the guess flips sign and doubles in size every step — "
            "$1,-2,4,-8,\\ldots$ — running screaming away from the very root it "
            "was meant to find. Same elegant formula; the difference is whether "
            "the slope behaves at the root."
        ),
        nbb.code(
            "def _newton_panel(which='g(x) = x\\u00b2 \\u2212 2   (root \\u221a2)', steps=4):\n"
            "    if which.startswith('g(x)'):\n"
            "        f  = lambda x: x**2 - 2.0\n"
            "        fp = lambda x: 2.0 * x\n"
            "        x0, root = 1.5, np.sqrt(2.0)\n"
            "        title = 'Newton on  g(x) = x\\u00b2 \\u2212 2   \\u2192   \\u221a2'\n"
            "        gx = np.linspace(0.4, 2.2, 400)\n"
            "        good = True\n"
            "    else:\n"
            "        # Real cube root, sign-aware: cbrt blows up under Newton.\n"
            "        f  = lambda x: np.cbrt(x)\n"
            "        fp = lambda x: (1.0 / 3.0) * np.cbrt(x) / np.where(x == 0, np.nan, x)\n"
            "        x0, root = 1.0, 0.0\n"
            "        title = 'Newton on  f(x) = x^(1/3)   (root 0) \\u2014 diverges'\n"
            "        gx = np.linspace(-9.0, 9.0, 400)\n"
            "        good = False\n"
            "\n"
            "    # Run Newton, recording each guess.\n"
            "    xs = [float(x0)]\n"
            "    for _ in range(steps):\n"
            "        x = xs[-1]\n"
            "        d = fp(x)\n"
            "        if d == 0 or not np.isfinite(d):\n"
            "            break\n"
            "        nxt = x - f(x) / d\n"
            "        if not np.isfinite(nxt) or abs(nxt) > 1e9:\n"
            "            xs.append(nxt); break\n"
            "        xs.append(nxt)\n"
            "    xs = np.array(xs)\n"
            "\n"
            "    fig, ax = plt.subplots(figsize=(7.6, 4.6))\n"
            "    axes(ax, title)\n"
            "    ax.axhline(0.0, color=GRAY, lw=1.0)\n"
            "    ax.plot(gx, f(gx), color=BLUE, lw=2.4, zorder=1)\n"
            "    ax.scatter([root], [0.0], s=110, color=GREEN, zorder=6,\n"
            "               marker='*', label=f'true root = {root:.4g}')\n"
            "    # Draw the tangent slides for the first few steps (the geometry).\n"
            "    shown = min(len(xs) - 1, 4)\n"
            "    for i in range(shown):\n"
            "        x = xs[i]\n"
            "        if not np.isfinite(x):\n"
            "            continue\n"
            "        ax.plot([x, x], [0.0, f(x)], color=PURPLE, lw=1.0, ls=':',\n"
            "                zorder=2)\n"
            "        ax.plot([x, xs[i + 1]], [f(x), 0.0], color=PURPLE, lw=1.4,\n"
            "                zorder=2)\n"
            "    vis = np.isfinite(xs) & (np.abs(xs) <= np.abs(gx).max())\n"
            "    ax.scatter(xs[vis], f(xs[vis]), s=45, color=PURPLE, zorder=5,\n"
            "               label='Newton guesses')\n"
            "    ax.set_xlabel('x'); ax.set_ylabel('y')\n"
            "    ax.set_xlim(gx.min(), gx.max())\n"
            "    ax.legend(loc='upper left', framealpha=0.9, fontsize=9)\n"
            "    plt.show()\n"
            "\n"
            "    # The convergence table — the heart of this panel.\n"
            "    rows = ['| step | guess $x_n$ | error $|x_n-\\\\text{root}|$ | correct digits |',\n"
            "            '|:---:|:---|:---|:---:|']\n"
            "    for n, x in enumerate(xs):\n"
            "        if not np.isfinite(x):\n"
            "            rows.append(f'| $x_{{{n}}}$ | overflow | \\u2014 | \\u2014 |')\n"
            "            continue\n"
            "        err = abs(x - root)\n"
            "        if err == 0:\n"
            "            dig = '\\u221e'\n"
            "        elif err >= 1:\n"
            "            dig = '0'\n"
            "        else:\n"
            "            dig = f'{-np.log10(err):.1f}'\n"
            "        rows.append(f'| $x_{{{n}}}$ | {x:.12g} | {err:.3e} | {dig} |')\n"
            "    note = ('Watch the **correct digits roughly double** each step '\n"
            "            '\\u2014 quadratic convergence.' if good else\n"
            "            'The error **doubles** each step ($x_{n+1}=-2x_n$): '\n"
            "            'Newton runs away from the root.')\n"
            "    display(Markdown('\\n'.join(rows) + '\\n\\n' + note))\n"
            "\n"
            "interact(_newton_panel,\n"
            "         which=Dropdown(\n"
            "             options=['g(x) = x\\u00b2 \\u2212 2   (root \\u221a2)',\n"
            "                      'f(x) = x^(1/3)   (root 0, blows up)'],\n"
            "             value='g(x) = x\\u00b2 \\u2212 2   (root \\u221a2)',\n"
            "             description='function'),\n"
            "         steps=IntSlider(value=4, min=1, max=10, step=1,\n"
            "                         description='steps'));"
        ),

        # ===============================================================
        # Widget 3 — the two-valley landscape (local vs global minimum)
        # ===============================================================
        nbb.md(
            "## 3. Two valleys — where you *start* decides where you *land*\n\n"
            "Real loss landscapes are not single bowls; they have several "
            "valleys, and gradient descent only ever finds *a* nearby one — not "
            "necessarily the best one. Here is the smallest landscape that shows "
            "it, $f(x)=x^4-3x^2+x$. Its slope is $f'(x)=4x^3-6x+1$, which is "
            "zero at three places: two **minima** (a shallow one on the left, a "
            "deeper one on the right) with a hill between them.\n\n"
            "Drag the **start** $x_0$ and watch the red path roll downhill. "
            "Start on the left of the hill and you fall into the shallow "
            "(worse) minimum; start on the right and you reach the deeper "
            "(better) one. Nothing about the descent changed — only where you "
            "began. *That* is the difference between a **local** and a "
            "**global** minimum, and it is the central headache of training a "
            "model: gradient descent finds the valley you happened to be "
            "standing over."
        ),
        nbb.code(
            "# Precompute the two true minima of f(x)=x^4-3x^2+x via f'(x)=4x^3-6x+1.\n"
            "_F3   = lambda x: x**4 - 3.0 * x**2 + x\n"
            "_F3P  = lambda x: 4.0 * x**3 - 6.0 * x + 1.0\n"
            "_CRIT = np.roots([4.0, 0.0, -6.0, 1.0]).real\n"
            "_CRIT = np.sort(_CRIT)\n"
            "_MINS = np.array([c for c in _CRIT if (12.0 * c**2 - 6.0) > 0])  # f''>0\n"
            "\n"
            "def _two_valleys(x0=-1.6, eta=0.02, n_steps=40):\n"
            "    xs = [float(x0)]\n"
            "    for _ in range(n_steps):\n"
            "        nxt = xs[-1] - eta * _F3P(xs[-1])\n"
            "        if not np.isfinite(nxt) or abs(nxt) > 1e6:\n"
            "            xs.append(nxt); break\n"
            "        xs.append(nxt)\n"
            "        if abs(_F3P(xs[-1])) < 1e-9:\n"
            "            break\n"
            "    xs = np.array(xs)\n"
            "    landed = xs[-1]\n"
            "    # Which true minimum did we land nearest?\n"
            "    target = _MINS[np.argmin(np.abs(_MINS - landed))] if np.isfinite(landed) else np.nan\n"
            "    glob = _MINS[np.argmin(_F3(_MINS))]\n"
            "    is_global = np.isfinite(landed) and abs(target - glob) < 1e-6\n"
            "\n"
            "    fig, ax = plt.subplots(figsize=(8.2, 4.8))\n"
            "    axes(ax, 'two-valley landscape  f(x) = x\\u2074 \\u2212 3x\\u00b2 + x')\n"
            "    gx = np.linspace(-2.1, 2.1, 500)\n"
            "    ax.plot(gx, _F3(gx), color=BLUE, lw=2.4, zorder=1, label='f(x)')\n"
            "    # Mark both minima; star the global one.\n"
            "    for m in _MINS:\n"
            "        is_g = abs(m - glob) < 1e-6\n"
            "        ax.scatter([m], [_F3(m)], s=150 if is_g else 90,\n"
            "                   color=GREEN, zorder=5,\n"
            "                   marker='*' if is_g else 'o',\n"
            "                   label=('global min' if is_g else 'local min'))\n"
            "    vis = np.isfinite(xs)\n"
            "    ax.plot(xs[vis], _F3(xs[vis]), '-', color=RED, lw=1.4, zorder=3)\n"
            "    ax.scatter(xs[vis], _F3(xs[vis]), s=26, color=RED, zorder=4,\n"
            "               label='descent path')\n"
            "    ax.scatter([x0], [_F3(x0)], s=110, color=DARK, marker='s',\n"
            "               zorder=6, label='start x\\u2080')\n"
            "    ax.set_xlabel('x'); ax.set_ylabel('f(x)')\n"
            "    ax.set_xlim(-2.1, 2.1)\n"
            "    ax.set_ylim(_F3(gx).min() - 0.4, _F3(_CRIT[1]) + 1.0)\n"
            "    ax.legend(loc='upper center', framealpha=0.9, fontsize=9, ncol=2)\n"
            "    plt.show()\n"
            "\n"
            "    verdict = ('reached the **global** minimum \\u2713' if is_global\n"
            "               else 'trapped in a **local** (worse) minimum \\u2717')\n"
            "    display(Markdown(\n"
            "        f'Started at $x_0={x0:.2f}$ \\u2192 landed at '\n"
            "        f'$x\\\\approx{landed:.4f}$ with '\n"
            "        f'$f={_F3(landed):.4f}$ \\u2014 {verdict}.  '\n"
            "        f'(Global min sits at $x\\\\approx{glob:.4f}$, '\n"
            "        f'$f\\\\approx{_F3(glob):.4f}$.)'))\n"
            "\n"
            "interact(_two_valleys,\n"
            "         x0=FloatSlider(value=-1.6, min=-2.0, max=2.0, step=0.05,\n"
            "                        description='start x\\u2080'),\n"
            "         eta=FloatSlider(value=0.02, min=0.005, max=0.06, step=0.005,\n"
            "                         description='\\u03b7 (rate)', readout_format='.3f'),\n"
            "         n_steps=IntSlider(value=40, min=5, max=80, step=5,\n"
            "                           description='steps'));"
        ),

        # ===============================================================
        # Widget 4 — Newton vs gradient descent, step counter
        # ===============================================================
        nbb.md(
            "## 4. The race — Newton vs. gradient descent, counted in steps\n\n"
            "The two methods are secretly the same idea: both step against the "
            "slope $f'$. Gradient descent uses a fixed step size $\\eta$ that "
            "*you* pick; Newton uses $1/f''(x_n)$, reading the curvature off the "
            "function and setting its own step size. Let us race them on the "
            "same job — minimizing a convex $f$ by driving $f'$ to zero — and "
            "**count the steps each needs** to get within a tolerance.\n\n"
            "On a quadratic $f(x)=\\tfrac{a}{2}x^2$ Newton lands in a **single "
            "step** from anywhere (its automatic step size $1/f''=1/a$ is "
            "exactly the perfect $\\eta$). Gradient descent needs many, and how "
            "many depends on the $\\eta$ you chose. Slide $\\eta$ and the "
            "curvature $a$ and watch Newton win by a landslide — the lesson "
            "behind *why* Newton is the fast method (and Section 5 shows the "
            "catch that keeps AI from using it)."
        ),
        nbb.code(
            "def _race(a=2.0, eta=0.3, x0=2.5, tol=1e-6, max_steps=200):\n"
            "    f   = lambda x: 0.5 * a * x**2\n"
            "    fp  = lambda x: a * x\n"
            "    fpp = lambda x: a\n"
            "    xmin = 0.0\n"
            "\n"
            "    # Gradient descent on f.\n"
            "    gd = [float(x0)]\n"
            "    for _ in range(max_steps):\n"
            "        gd.append(gd[-1] - eta * fp(gd[-1]))\n"
            "        if not np.isfinite(gd[-1]) or abs(gd[-1]) > 1e9:\n"
            "            break\n"
            "        if abs(gd[-1] - xmin) < tol:\n"
            "            break\n"
            "    gd = np.array(gd)\n"
            "    gd_steps = len(gd) - 1\n"
            "    gd_ok = np.isfinite(gd[-1]) and abs(gd[-1] - xmin) < tol\n"
            "\n"
            "    # Newton on f' (i.e. x - f'/f'') to find the minimum.\n"
            "    nt = [float(x0)]\n"
            "    for _ in range(max_steps):\n"
            "        nt.append(nt[-1] - fp(nt[-1]) / fpp(nt[-1]))\n"
            "        if abs(nt[-1] - xmin) < tol:\n"
            "            break\n"
            "    nt = np.array(nt)\n"
            "    nt_steps = len(nt) - 1\n"
            "\n"
            "    fig, ax = plt.subplots(figsize=(8.0, 4.6))\n"
            "    axes(ax, f'distance to the minimum vs. step   (a = {a:.2g}, \\u03b7 = {eta:.2g})')\n"
            "    ax.semilogy(np.arange(len(gd)), np.abs(gd - xmin) + 1e-16, '-o',\n"
            "                color=RED, ms=5, label=f'gradient descent ({gd_steps} steps)')\n"
            "    ax.semilogy(np.arange(len(nt)), np.abs(nt - xmin) + 1e-16, '-s',\n"
            "                color=PURPLE, ms=6, label=f'Newton ({nt_steps} step'\n"
            "                f'{\"s\" if nt_steps != 1 else \"\"})')\n"
            "    ax.axhline(tol, color=GREEN, lw=1.4, ls='--', label=f'tolerance {tol:g}')\n"
            "    ax.set_xlabel('step'); ax.set_ylabel('|x \\u2212 x*|  (log scale)')\n"
            "    ax.legend(loc='upper right', framealpha=0.9, fontsize=9)\n"
            "    plt.show()\n"
            "\n"
            "    winner = ('Newton' if nt_steps < gd_steps else\n"
            "              'gradient descent' if gd_steps < nt_steps else 'a tie')\n"
            "    gd_txt = f'**{gd_steps}** steps' + ('' if gd_ok else ' (did not converge)')\n"
            "    display(Markdown(\n"
            "        f'**Steps to reach tolerance {tol:g}:**  '\n"
            "        f'Newton = **{nt_steps}**, gradient descent = {gd_txt}.  '\n"
            "        f'Winner: **{winner}**.  '\n"
            "        f'(On a quadratic, Newton\\u2019s step size $1/f\\'\\'=1/{a:.2g}$ '\n"
            "        f'is the exact best $\\\\eta$, so it lands in one step.)'))\n"
            "\n"
            "interact(_race,\n"
            "         a=FloatSlider(value=2.0, min=0.5, max=8.0, step=0.5,\n"
            "                       description='curvature a'),\n"
            "         eta=FloatSlider(value=0.3, min=0.02, max=0.9, step=0.02,\n"
            "                         description='\\u03b7 (GD rate)', readout_format='.2f'),\n"
            "         x0=FloatSlider(value=2.5, min=-4.0, max=4.0, step=0.5,\n"
            "                        description='start x\\u2080'));"
        ),

        # ===============================================================
        # Widget 5 — momentum on a stretched (ill-conditioned) bowl
        # ===============================================================
        nbb.md(
            "## 5. Your first real optimizer — momentum on a steep bowl\n\n"
            "On a *steep*, ill-conditioned bowl $f(x)=k\\,x^2$ (large $k$ means "
            "sharp curvature), plain gradient descent is forced to take tiny "
            "steps: its safe range $0<\\eta<\\tfrac1k$ collapses as $k$ grows, "
            "so it crawls. **Momentum** — the heavy-ball method — fixes this by "
            "letting the steps build up speed, like a ball gathering momentum "
            "rolling downhill:\n\n"
            "$$v_{k+1}=\\beta\\,v_k-\\eta\\,f'(x_k),\\qquad x_{k+1}=x_k+v_{k+1}.$$\n\n"
            "The velocity $v$ remembers past steps (the factor $\\beta$, here "
            "$0.9$); plain gradient descent is just the $\\beta=0$ case. Tick "
            "the **momentum** box to overlay the heavy-ball path (teal) on the "
            "plain one (red), and compare how many steps each needs. This is a "
            "baby version of the optimizers that actually train neural "
            "networks — and your bridge to Book 3, where $x$ becomes a vector "
            "and this exact rule does the heavy lifting."
        ),
        nbb.code(
            "def _momentum(k=10.0, eta=0.05, beta=0.9, use_momentum=True,\n"
            "              x0=1.0, tol=1e-4, max_steps=120):\n"
            "    fp = lambda x: 2.0 * k * x\n"
            "    f  = lambda x: k * x**2\n"
            "    xmin = 0.0\n"
            "\n"
            "    def run(mom):\n"
            "        xs = [float(x0)]; v = 0.0\n"
            "        for _ in range(max_steps):\n"
            "            v = (beta * v if mom else 0.0) - eta * fp(xs[-1])\n"
            "            nxt = xs[-1] + v\n"
            "            xs.append(nxt)\n"
            "            if not np.isfinite(nxt) or abs(nxt) > 1e9:\n"
            "                break\n"
            "            if abs(nxt - xmin) < tol:\n"
            "                break\n"
            "        return np.array(xs)\n"
            "\n"
            "    plain = run(False)\n"
            "    heavy = run(True)\n"
            "\n"
            "    fig, (axL, axR) = plt.subplots(1, 2, figsize=(11.0, 4.6))\n"
            "\n"
            "    # --- left: paths on the steep bowl ---\n"
            "    axes(axL, f'paths on the steep bowl  f(x) = {k:.0f}\\u00b7x\\u00b2')\n"
            "    span = max(abs(x0) * 1.2, 1.0)\n"
            "    gx = np.linspace(-span, span, 400)\n"
            "    axL.plot(gx, f(gx), color=BLUE, lw=2.2, zorder=1, label='f(x)')\n"
            "    pv = np.isfinite(plain) & (np.abs(plain) <= span)\n"
            "    axL.plot(plain[pv], f(plain[pv]), '-o', color=RED, ms=4, zorder=3,\n"
            "             label=f'plain GD ({len(plain) - 1} steps)')\n"
            "    if use_momentum:\n"
            "        hv = np.isfinite(heavy) & (np.abs(heavy) <= span)\n"
            "        axL.plot(heavy[hv], f(heavy[hv]), '-s', color=TEAL, ms=5,\n"
            "                 zorder=4, label=f'momentum ({len(heavy) - 1} steps)')\n"
            "    axL.scatter([0], [0], s=140, color=GREEN, marker='*', zorder=6)\n"
            "    axL.set_xlabel('x'); axL.set_ylabel('f(x)')\n"
            "    axL.set_xlim(-span, span); axL.set_ylim(-0.05 * f(span), f(span))\n"
            "    axL.legend(loc='upper center', framealpha=0.9, fontsize=9)\n"
            "\n"
            "    # --- right: convergence speed ---\n"
            "    axes(axR, 'distance to minimum vs. step')\n"
            "    axR.semilogy(np.arange(len(plain)), np.abs(plain - xmin) + 1e-16,\n"
            "                 '-o', color=RED, ms=4, label='plain GD')\n"
            "    if use_momentum:\n"
            "        axR.semilogy(np.arange(len(heavy)), np.abs(heavy - xmin) + 1e-16,\n"
            "                     '-s', color=TEAL, ms=5, label='momentum')\n"
            "    axR.axhline(tol, color=GREEN, lw=1.3, ls='--', label=f'tol {tol:g}')\n"
            "    axR.set_xlabel('step'); axR.set_ylabel('|x \\u2212 x*|  (log)')\n"
            "    axR.legend(loc='upper right', framealpha=0.9, fontsize=9)\n"
            "    fig.tight_layout()\n"
            "    plt.show()\n"
            "\n"
            "    if use_momentum:\n"
            "        p, h = len(plain) - 1, len(heavy) - 1\n"
            "        verdict = (f'Momentum reached tolerance in **{h}** steps vs. '\n"
            "                   f'**{p}** for plain gradient descent'\n"
            "                   + (f' \\u2014 a {p / h:.1f}\\u00d7 speed-up.' if h and h < p\n"
            "                      else '.'))\n"
            "    else:\n"
            "        verdict = ('Momentum is **off** ($\\\\beta=0$): this is plain '\n"
            "                   'gradient descent. Tick the box to add the heavy ball.')\n"
            "    display(Markdown(verdict))\n"
            "\n"
            "interact(_momentum,\n"
            "         k=FloatSlider(value=10.0, min=1.0, max=30.0, step=1.0,\n"
            "                       description='steepness k'),\n"
            "         eta=FloatSlider(value=0.05, min=0.005, max=0.09, step=0.005,\n"
            "                         description='\\u03b7 (rate)', readout_format='.3f'),\n"
            "         beta=FloatSlider(value=0.9, min=0.0, max=0.95, step=0.05,\n"
            "                          description='\\u03b2 (momentum)', readout_format='.2f'),\n"
            "         use_momentum=Checkbox(value=True, description='momentum on'));"
        ),

        nbb.md(
            "---\n\n"
            "*Every widget here is the same chapter, run by hand: a guess that "
            "gets better each step. You watched a learning rate slide a glide "
            "into an explosion, Newton double its digits and then fly apart, a "
            "starting point alone decide local versus global, and a heavy ball "
            "outrun plain descent on a steep bowl. In Book 3 the single number "
            "$x$ becomes a vector and $f'$ becomes the **gradient** — but the "
            "update rule $x_{k+1}=x_k-\\eta\\,(\\text{gradient})$ keeps the exact "
            "same shape. When you next watch a neural network's loss tick "
            "downward, you will be watching this notebook, run a few million "
            "times.*"
        ),
    ]
    nbb.build("ch9_newton_gradient_descent.ipynb", cells)


if __name__ == "__main__":
    build()
