"""Builder for the Chapter 11 companion notebook (the Fundamental Theorem).

Run:
    /opt/anaconda3/bin/python nb_ch11.py
emits ch11_fundamental_theorem.ipynb in this folder. Validate by executing
with nbconvert.
"""
import nbbuild as nbb

TITLE = "The Fundamental Theorem of Calculus"
SUBTITLE = ("why finding an area is the same as undoing a derivative "
            "— the summit of the book")
BLURB = (
    "Four live pictures of the chapter's one idea and its payoff: slide the "
    "right edge of an area and watch its growth rate land exactly on the "
    "curve (Part 1); turn a definite integral into a single subtraction "
    "$F(b)-F(a)$ (Part 2); run the product rule backward with integration "
    "by parts; and, as the book's final act, watch $\\ln x$ appear as the "
    "area under $1/t$ and find $e$ as the place that area first hits $1$."
)


def build():
    cells = [
        nbb.header(11, TITLE, SUBTITLE, BLURB),
        nbb.setup_cell(),

        # ---------------------------------------------------------------
        # Widget 1 — The moving edge (FTC Part 1)
        # ---------------------------------------------------------------
        nbb.md(
            "## 1. The moving edge — FTC Part 1\n\n"
            "Fix the left edge at $a$ and let the **right edge** $x$ slide. "
            "Define the *area-so-far function*\n\n"
            "$$A(x) = \\int_a^x f(t)\\,dt,$$\n\n"
            "the signed area under $f$ from $a$ out to $x$. The whole theorem "
            "is the answer to one question: *how fast does this area grow as "
            "$x$ moves right?* Push the edge out by a sliver $h$ and the area "
            "gains a thin strip of width $h$ and height about $f(x)$ — so the "
            "growth rate is the height of the curve. In symbols, **Part 1**:\n\n"
            "$$A'(x) = f(x).$$\n\n"
            "Pick a curve and drag $x$. The **top** panel shades $A(x)$ in "
            "green and shows the strip being added at the right edge. The "
            "**bottom** panel plots the accumulated area $A(x)$ in red, and "
            "overlays its *numerical* derivative $A'(x)$ as a green dashed "
            "line — watch it land exactly on the blue dot $f(x)$. The "
            "Fundamental Theorem, seen live — *(Figure 11.1)*."
        ),
        nbb.code(
            "_CURVES1 = {\n"
            "    'f(t) = sin(t) + 1.5':   (lambda t: np.sin(t) + 1.5,  0.0, 6.2),\n"
            "    'f(t) = t^2':            (lambda t: t**2,             0.0, 2.4),\n"
            "    'f(t) = 0.5 t + 0.5':    (lambda t: 0.5*t + 0.5,      0.0, 4.0),\n"
            "    'f(t) = e^{t/3}':        (lambda t: np.exp(t/3),      0.0, 4.0),\n"
            "    'f(t) = 4 - (t-2)^2':    (lambda t: 4 - (t-2)**2,     0.0, 4.0),\n"
            "}\n"
            "\n"
            "def _area_to(f, a, x, n=600):\n"
            "    '''Numerical signed area A(x) = int_a^x f, via the trapezoid rule.'''\n"
            "    if x <= a:\n"
            "        return 0.0\n"
            "    ts = np.linspace(a, x, n)\n"
            "    return float(np.trapz(f(ts), ts))\n"
            "\n"
            "def _moving_edge(curve='f(t) = sin(t) + 1.5', x=3.0):\n"
            "    f, a, b = _CURVES1[curve]\n"
            "    x = min(max(x, a + 0.05), b)            # keep x inside [a, b]\n"
            "\n"
            "    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7.2, 6.8),\n"
            "                                   sharex=True)\n"
            "    ts = np.linspace(a, b, 600)\n"
            "    ys = f(ts)\n"
            "\n"
            "    # --- Top: the curve and the shaded area A(x). ---\n"
            "    ax1.plot(ts, ys, color=BLUE, lw=2.4, label='$f(t)$', zorder=3)\n"
            "    mask = ts <= x\n"
            "    ax1.fill_between(ts[mask], 0, ys[mask], color=SHADEG,\n"
            "                     alpha=0.95, zorder=1,\n"
            "                     label='area $A(x)=\\\\int_a^x f$')\n"
            "    # The thin strip added at the right edge.\n"
            "    h = 0.10 * (b - a)\n"
            "    xs = np.linspace(x, min(x + h, b), 30)\n"
            "    ax1.fill_between(xs, 0, f(xs), color=RED, alpha=0.45, zorder=2,\n"
            "                     label='new strip ($\\\\approx f(x)\\\\,h$)')\n"
            "    ax1.axvline(x, color=RED, lw=1.2, ls=':')\n"
            "    ax1.scatter([x], [f(x)], s=70, color=BLUE, zorder=6)\n"
            "    ax1.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax1.set_ylabel('$f(t)$')\n"
            "    ax1.set_title(f'Area so far:  $A(x) \\\\approx$ {_area_to(f, a, x):.3f}',\n"
            "                  color=DARK)\n"
            "    ax1.legend(loc='upper left', framealpha=0.9, fontsize=9)\n"
            "\n"
            "    # --- Bottom: A(x) and its numerical derivative vs f. ---\n"
            "    xx = np.linspace(a, b, 200)\n"
            "    Avals = np.array([_area_to(f, a, t) for t in xx])\n"
            "    dA = np.gradient(Avals, xx)            # numerical A'(x)\n"
            "    ax2.plot(xx, Avals, color=RED, lw=2.4, label='$A(x)$', zorder=3)\n"
            "    ax2.plot(xx, dA, color=GREEN, lw=2.2, ls='--',\n"
            "             label=\"$A'(x)$ (numerical)\", zorder=4)\n"
            "    ax2.plot(ts, ys, color=BLUE, lw=1.4, alpha=0.55,\n"
            "             label='$f(t)$', zorder=2)\n"
            "    ax2.scatter([x], [f(x)], s=70, color=BLUE, zorder=6)\n"
            "    ax2.scatter([x], [_area_to(f, a, x)], s=70, color=RED, zorder=6)\n"
            "    ax2.axvline(x, color=RED, lw=1.2, ls=':')\n"
            "    ax2.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax2.set_xlabel('$x$')\n"
            "    ax2.set_title(\"$A'(x)$ (green dashed) lands on $f(x)$ (blue) \"\n"
            "                  \"\\u2014 Part 1\", color=DARK)\n"
            "    ax2.legend(loc='upper left', framealpha=0.9, fontsize=9)\n"
            "    plt.tight_layout()\n"
            "    plt.show()\n"
            "\n"
            "interact(_moving_edge,\n"
            "         curve=Dropdown(options=list(_CURVES1), description='curve'),\n"
            "         x=FloatSlider(value=3.0, min=0.1, max=6.2, step=0.1,\n"
            "                       description='right edge x'));\n"
        ),

        # ---------------------------------------------------------------
        # Widget 2 — FTC evaluator (Part 2): area = F(b) - F(a)
        # ---------------------------------------------------------------
        nbb.md(
            "## 2. Area becomes a subtraction — FTC Part 2\n\n"
            "Since $A(x)=\\int_a^x f$ is *an* antiderivative of $f$ (Part 1), "
            "and any other antiderivative $F$ differs from it only by a "
            "constant, the laborious definite integral collapses into "
            "arithmetic. **Part 2:**\n\n"
            "$$\\int_a^b f(x)\\,dx = F(b) - F(a) = \\big[F(x)\\big]_a^b.$$\n\n"
            "Find an antiderivative, plug in the endpoints, subtract. Pick a "
            "pair $(f, F)$ and drag the endpoints $a$ and $b$. The shaded "
            "green area under $f$ (top) equals the **rise** of $F$ between "
            "the two marked endpoint values $F(a)$ and $F(b)$ (bottom). Read "
            "the title: the trapezoid-rule area and $F(b)-F(a)$ agree to the "
            "decimal."
        ),
        nbb.code(
            "# Each preset: (f, F) with F' = f, plus a default [a, b] window.\n"
            "_PAIRS = {\n"
            "    'f=x^2,  F=x^3/3':\n"
            "        (lambda x: x**2, lambda x: x**3/3, -1.5, 2.0),\n"
            "    'f=sin x,  F=-cos x':\n"
            "        (lambda x: np.sin(x), lambda x: -np.cos(x), 0.0, np.pi),\n"
            "    'f=cos x,  F=sin x':\n"
            "        (lambda x: np.cos(x), lambda x: np.sin(x), 0.0, np.pi/2),\n"
            "    'f=e^x,  F=e^x':\n"
            "        (lambda x: np.exp(x), lambda x: np.exp(x), 0.0, 1.5),\n"
            "    'f=1/x,  F=ln x':\n"
            "        (lambda x: 1.0/x, lambda x: np.log(x), 1.0, 3.0),\n"
            "    'f=2x+1,  F=x^2+x':\n"
            "        (lambda x: 2*x + 1, lambda x: x**2 + x, -1.0, 2.0),\n"
            "}\n"
            "\n"
            "def _trap_area(f, a, b, n=800):\n"
            "    ts = np.linspace(a, b, n)\n"
            "    return float(np.trapz(f(ts), ts))\n"
            "\n"
            "def _ftc2(pair='f=x^2,  F=x^3/3', a=0.0, b=1.0):\n"
            "    f, F, _, _ = _PAIRS[pair]\n"
            "    if b - a < 0.2:\n"
            "        b = a + 0.2\n"
            "    lo, hi = min(a, b), max(a, b)\n"
            "    pad = 0.35 * (hi - lo) + 0.2\n"
            "    xs = np.linspace(lo - pad, hi + pad, 600)\n"
            "    # 1/x and ln need a positive window; clip safely.\n"
            "    if 'ln x' in pair or '1/x' in pair:\n"
            "        xs = xs[xs > 1e-3]\n"
            "\n"
            "    area = _trap_area(f, a, b)\n"
            "    exact = F(b) - F(a)\n"
            "\n"
            "    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7.2, 6.8),\n"
            "                                   sharex=True)\n"
            "    # --- Top: f with the area from a to b shaded. ---\n"
            "    ax1.plot(xs, f(xs), color=BLUE, lw=2.4, label='$f(x)$', zorder=3)\n"
            "    fillx = np.linspace(a, b, 400)\n"
            "    ax1.fill_between(fillx, 0, f(fillx), color=SHADEG, alpha=0.95,\n"
            "                     zorder=1, label='$\\\\int_a^b f$')\n"
            "    ax1.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax1.axvline(a, color=RED, lw=1.0, ls=':')\n"
            "    ax1.axvline(b, color=RED, lw=1.0, ls=':')\n"
            "    ax1.set_ylabel('$f(x)$')\n"
            "    ax1.set_title(f'Area $\\\\int_a^b f$ = {area:.4f}', color=DARK)\n"
            "    ax1.legend(loc='best', framealpha=0.9, fontsize=10)\n"
            "\n"
            "    # --- Bottom: F with the endpoint values and their rise. ---\n"
            "    ax2.plot(xs, F(xs), color=ORANGE, lw=2.4, label='$F(x)$',\n"
            "             zorder=3)\n"
            "    Fa, Fb = F(a), F(b)\n"
            "    ax2.scatter([a, b], [Fa, Fb], s=80, color=RED, zorder=6)\n"
            "    ax2.annotate(f'$F(a)$ = {Fa:.3f}', xy=(a, Fa),\n"
            "                 xytext=(6, -14), textcoords='offset points',\n"
            "                 color=RED, fontsize=10)\n"
            "    ax2.annotate(f'$F(b)$ = {Fb:.3f}', xy=(b, Fb),\n"
            "                 xytext=(6, 8), textcoords='offset points',\n"
            "                 color=RED, fontsize=10)\n"
            "    # The rise F(b) - F(a), drawn as a vertical gap at x = b.\n"
            "    ax2.plot([b, b], [Fa, Fb], color=GREEN, lw=3.0, alpha=0.8,\n"
            "             zorder=4, label='rise $F(b)-F(a)$')\n"
            "    ax2.plot([a, b], [Fa, Fa], color=GREEN, lw=1.0, ls=':',\n"
            "             zorder=2)\n"
            "    ax2.axvline(a, color=RED, lw=1.0, ls=':')\n"
            "    ax2.axvline(b, color=RED, lw=1.0, ls=':')\n"
            "    ax2.set_xlabel('$x$')\n"
            "    ax2.set_title(f'$F(b)-F(a)$ = {exact:.4f}   '\n"
            "                  f'(matches the area)', color=DARK)\n"
            "    ax2.legend(loc='best', framealpha=0.9, fontsize=10)\n"
            "    plt.tight_layout()\n"
            "    plt.show()\n"
            "\n"
            "interact(_ftc2,\n"
            "         pair=Dropdown(options=list(_PAIRS), description='(f, F)'),\n"
            "         a=FloatSlider(value=0.0, min=-1.5, max=2.0, step=0.1,\n"
            "                       description='a'),\n"
            "         b=FloatSlider(value=1.0, min=-1.0, max=3.0, step=0.1,\n"
            "                       description='b'));\n"
        ),

        # ---------------------------------------------------------------
        # Widget 3 — Integration-by-parts workbench
        # ---------------------------------------------------------------
        nbb.md(
            "## 3. Integration by parts — the product rule, backward\n\n"
            "The product rule integrated and rearranged is\n\n"
            "$$\\int u\\,dv = uv - \\int v\\,du.$$\n\n"
            "Use it when the integrand is a product and differentiating one "
            "factor makes the leftover integral *simpler*. Choose that factor "
            "to be $u$ (it gets differentiated) and the rest to be $dv$ (it "
            "gets integrated). Pick an example: the widget prints the "
            "$u,\\,dv,\\,v,\\,du$ bookkeeping and the resulting "
            "$uv-\\int v\\,du$, then plots the integrand (blue) and its "
            "antiderivative (orange). Check visually that the orange curve's "
            "slope *is* the blue curve."
        ),
        nbb.code(
            "# Each example: integrand, its antiderivative, and the parts table.\n"
            "_PARTS = {\n"
            "    'int x e^x dx': dict(\n"
            "        integrand=lambda x: x*np.exp(x),\n"
            "        antideriv=lambda x: (x - 1)*np.exp(x),\n"
            "        u='x', dv='e^x dx', v='e^x', du='1 dx',\n"
            "        result=r'x e^x - \\int e^x\\,dx = (x-1)e^x + C',\n"
            "        xlim=(-3.0, 2.0)),\n"
            "    'int x sin x dx': dict(\n"
            "        integrand=lambda x: x*np.sin(x),\n"
            "        antideriv=lambda x: np.sin(x) - x*np.cos(x),\n"
            "        u='x', dv='sin x dx', v='-cos x', du='1 dx',\n"
            "        result=r'-x\\cos x - \\int(-\\cos x)\\,dx = \\sin x - x\\cos x + C',\n"
            "        xlim=(-2*np.pi, 2*np.pi)),\n"
            "    'int x cos x dx': dict(\n"
            "        integrand=lambda x: x*np.cos(x),\n"
            "        antideriv=lambda x: np.cos(x) + x*np.sin(x),\n"
            "        u='x', dv='cos x dx', v='sin x', du='1 dx',\n"
            "        result=r'x\\sin x - \\int \\sin x\\,dx = \\cos x + x\\sin x + C',\n"
            "        xlim=(-2*np.pi, 2*np.pi)),\n"
            "    'int ln x dx': dict(\n"
            "        integrand=lambda x: np.log(x),\n"
            "        antideriv=lambda x: x*np.log(x) - x,\n"
            "        u='ln x', dv='dx', v='x', du='(1/x) dx',\n"
            "        result=r'x\\ln x - \\int x\\cdot\\tfrac1x\\,dx = x\\ln x - x + C',\n"
            "        xlim=(0.05, 4.0)),\n"
            "}\n"
            "\n"
            "def _byparts(example='int x e^x dx'):\n"
            "    d = _PARTS[example]\n"
            "    # Render the bookkeeping table and the result as LaTeX/Markdown.\n"
            "    table = (\n"
            "        '| choose | differentiate | integrate |\\n'\n"
            "        '|---|---|---|\\n'\n"
            "        f'| $u = {d[\"u\"]}$ | $du = {d[\"du\"]}$ |  |\\n'\n"
            "        f'| $dv = {d[\"dv\"]}$ |  | $v = {d[\"v\"]}$ |\\n'\n"
            "    )\n"
            "    display(Markdown(\n"
            "        f'**Bookkeeping for $\\\\displaystyle\\\\int u\\\\,dv$:**\\n\\n'\n"
            "        + table +\n"
            "        f'\\n$$\\\\int u\\\\,dv = uv - \\\\int v\\\\,du = {d[\"result\"]}$$'\n"
            "    ))\n"
            "\n"
            "    lo, hi = d['xlim']\n"
            "    xs = np.linspace(lo, hi, 600)\n"
            "    fig, ax = plt.subplots()\n"
            "    ax.plot(xs, d['integrand'](xs), color=BLUE, lw=2.4,\n"
            "            label='integrand', zorder=3)\n"
            "    ax.plot(xs, d['antideriv'](xs), color=ORANGE, lw=2.4,\n"
            "            label='antiderivative (its slope = integrand)', zorder=3)\n"
            "    ax.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax.set_xlim(lo, hi)\n"
            "    ax.set_xlabel('$x$'); ax.set_ylabel('$y$')\n"
            "    ax.set_title('Integration by parts: integrand vs antiderivative',\n"
            "                 color=DARK)\n"
            "    ax.legend(loc='best', framealpha=0.9, fontsize=10)\n"
            "    plt.show()\n"
            "\n"
            "interact(_byparts,\n"
            "         example=Dropdown(options=list(_PARTS), description='example'));\n"
        ),

        # ---------------------------------------------------------------
        # Widget 4 — Log as area, and finding e
        # ---------------------------------------------------------------
        nbb.md(
            "## 4. The logarithm as an area, and finding $e$\n\n"
            "The book's final act. We *define* the natural logarithm as the "
            "area under $1/t$:\n\n"
            "$$\\ln x \\;:=\\; \\int_1^x \\frac{1}{t}\\,dt \\quad (x > 0).$$\n\n"
            "Drag $x$ and watch the green area accumulate; the title reports "
            "both the shaded area and $\\ln x$ — they are the same number. "
            "The vertical green marker shows where the area first reaches "
            "exactly $1$: that place is the number **$e$**. (For $x<1$ the "
            "integral runs backward, so the area is *negative* — exactly "
            "$\\ln x < 0$.) Every loan the book took on $e$, $\\ln$, and "
            "$e^x$ is repaid right here — *(Figure 11.2)*."
        ),
        nbb.code(
            "def _log_area(x=2.0):\n"
            "    lo_t, hi_t = 0.25, 6.0\n"
            "    ts = np.linspace(lo_t, hi_t, 800)\n"
            "    fig, ax = plt.subplots()\n"
            "    ax.plot(ts, 1.0/ts, color=BLUE, lw=2.4, label='$y = 1/t$',\n"
            "            zorder=3)\n"
            "\n"
            "    # Shade the signed area from 1 to x (green); area = ln x.\n"
            "    if x >= 1:\n"
            "        fx = np.linspace(1, x, 400)\n"
            "    else:\n"
            "        fx = np.linspace(x, 1, 400)\n"
            "    ax.fill_between(fx, 0, 1.0/fx, color=SHADEG, alpha=0.95,\n"
            "                    zorder=1, label='area $= \\\\ln x$')\n"
            "    area = float(np.log(x))            # = int_1^x dt/t, exactly\n"
            "\n"
            "    # Mark t = e, where the area from 1 first reaches exactly 1.\n"
            "    e = np.e\n"
            "    ax.axvline(e, color=GREEN, lw=2.0, ls='--', zorder=4)\n"
            "    ax.annotate('$t = e$  (area here $= 1$)', xy=(e, 1.0/e),\n"
            "                xytext=(e + 0.15, 0.62), color=GREEN, fontsize=11,\n"
            "                arrowprops=dict(arrowstyle='->', color=GREEN))\n"
            "    ax.scatter([e], [1.0/e], s=70, color=GREEN, zorder=6)\n"
            "    # Mark the movable right edge x.\n"
            "    ax.axvline(x, color=RED, lw=1.2, ls=':', zorder=4)\n"
            "    ax.scatter([x], [1.0/x], s=70, color=RED, zorder=6)\n"
            "    ax.axvline(1, color=GRAY, lw=1.0)\n"
            "    ax.axhline(0, color=GRAY, lw=0.8)\n"
            "\n"
            "    ax.set_xlim(lo_t, hi_t)\n"
            "    ax.set_ylim(0, 4.2)\n"
            "    ax.set_xlabel('$t$'); ax.set_ylabel('$1/t$')\n"
            "    ax.set_title(f'x = {x:.3f}:   area = {area:+.4f}   '\n"
            "                 f'=   ln x = {area:+.4f}', color=DARK)\n"
            "    ax.legend(loc='upper right', framealpha=0.9, fontsize=10)\n"
            "    plt.show()\n"
            "\n"
            "interact(_log_area,\n"
            "         x=FloatSlider(value=2.0, min=0.3, max=6.0, step=0.05,\n"
            "                       description='right edge x'));\n"
        ),

        nbb.md(
            "---\n\n"
            "*Four windows onto one theorem. Widgets 1 and 2 are the two "
            "halves of the Fundamental Theorem — the area function's slope "
            "*is* the curve, so a definite integral is just $F(b)-F(a)$. "
            "Widget 3 is the product rule run backward. Widget 4 is the "
            "summit: $\\ln$ defined as an area, $e$ located as the place that "
            "area hits $1$, and every promissory note the book ever wrote "
            "paid in full. From here, Chapter 12 lets the sums run forever.*"
        ),
    ]
    nbb.build("ch11_fundamental_theorem.ipynb", cells)


if __name__ == "__main__":
    build()
