"""Builder for the Chapter 4 companion notebook (a toolkit for slopes).

Run:
    /opt/anaconda3/bin/python nb_ch4.py
emits ch4_rules.ipynb in this folder. Validate by executing with nbconvert.
"""
import nbbuild as nbb

TITLE = "A Toolkit for Slopes"
SUBTITLE = ("How to differentiate almost anything without ever touching a "
            "difference quotient again")
BLURB = (
    "Three live pictures of the differentiation rules: a **drill** that names "
    "which rule a function calls for and shows the worked derivative, a "
    "growing rectangle that *proves* the product rule $(fg)'=f'g+fg'$ by "
    "watching its two strips, and a chain-rule machine that assembles "
    "$f'(g(x))\\cdot g'(x)$ one factor at a time."
)


def build():
    cells = [
        nbb.header(4, TITLE, SUBTITLE, BLURB),
        nbb.setup_cell(),

        # ---------------------------------------------------------------
        # Widget 1 — Rule detector drill
        # ---------------------------------------------------------------
        nbb.md(
            "## 1. Rule detector\n\n"
            "Before you can *use* the rules you have to **see** which one a "
            "function is asking for. Pick a function from the dropdown; the "
            "blue curve is $f$ and the red curve is its derivative $f'$ "
            "(computed by hand, plotted for a reality check). Then tick "
            "**reveal** to name the rule(s) at work and read off the worked "
            "derivative.\n\n"
            "The whole game of this chapter is pattern recognition: a *power* "
            "($x^5$), a *product* (two factors multiplied, $x^2\\sin x$), a "
            "*quotient* (one thing over another, $\\tfrac{x}{x^2+1}$), or a "
            "*composition* — a function tucked **inside** another, "
            "$(x^2+1)^7$ or $\\sin 3x$ — which is the chain rule's territory."
        ),
        nbb.code(
            "# Each preset carries its f, its hand-computed f', the rule name,\n"
            "# and the worked steps (LaTeX) revealed on demand.\n"
            "_PRESETS = {\n"
            "    'x^5':\n"
            "        dict(f=lambda x: x**5, df=lambda x: 5*x**4,\n"
            "             rule='Power rule',\n"
            "             work=r'$\\frac{d}{dx}x^5 = 5x^{5-1} = 5x^4$',\n"
            "             note='Bring the exponent down, subtract one.'),\n"
            "    'x^2 * sin(x)':\n"
            "        dict(f=lambda x: x**2*np.sin(x),\n"
            "             df=lambda x: 2*x*np.sin(x) + x**2*np.cos(x),\n"
            "             rule='Product rule',\n"
            "             work=(r'$\\frac{d}{dx}\\big[x^2\\sin x\\big]'\n"
            "                   r'=(2x)\\sin x + x^2(\\cos x)$'),\n"
            "             note=\"first' \\u00b7 second + first \\u00b7 second'.\"),\n"
            "    '(x^2 + 1)^7':\n"
            "        dict(f=lambda x: (x**2 + 1)**7,\n"
            "             df=lambda x: 7*(x**2 + 1)**6 * 2*x,\n"
            "             rule='Chain rule',\n"
            "             work=(r'$\\frac{d}{dx}(x^2+1)^7'\n"
            "                   r'=7(x^2+1)^6\\cdot 2x = 14x(x^2+1)^6$'),\n"
            "             note='Outer (power) first, leave the inside alone, '\n"
            "                  'times the inside derivative.'),\n"
            "    'x / (x^2 + 1)':\n"
            "        dict(f=lambda x: x/(x**2 + 1),\n"
            "             df=lambda x: (1 - x**2)/(x**2 + 1)**2,\n"
            "             rule='Quotient rule',\n"
            "             work=(r'$\\frac{d}{dx}\\frac{x}{x^2+1}'\n"
            "                   r'=\\frac{(1)(x^2+1)-(x)(2x)}{(x^2+1)^2}'\n"
            "                   r'=\\frac{1-x^2}{(x^2+1)^2}$'),\n"
            "             note='Bottom \\u00b7 top\\u2032 \\u2212 top \\u00b7 '\n"
            "                  'bottom\\u2032, all over bottom squared.'),\n"
            "    'e^x * x':\n"
            "        dict(f=lambda x: np.exp(x)*x,\n"
            "             df=lambda x: np.exp(x)*x + np.exp(x),\n"
            "             rule='Product rule (with $e^x$)',\n"
            "             work=(r'$\\frac{d}{dx}\\big[e^x x\\big]'\n"
            "                   r'=e^x\\cdot x + e^x\\cdot 1 = e^x(x+1)$'),\n"
            "             note='$e^x$ is its own derivative; the rest is the '\n"
            "                  'product rule.'),\n"
            "    'sin(3x)':\n"
            "        dict(f=lambda x: np.sin(3*x),\n"
            "             df=lambda x: 3*np.cos(3*x),\n"
            "             rule='Chain rule',\n"
            "             work=(r'$\\frac{d}{dx}\\sin(3x)'\n"
            "                   r'=\\cos(3x)\\cdot 3 = 3\\cos(3x)$'),\n"
            "             note='Outer (sine) first, times the inside '\n"
            "                  'derivative $3$.'),\n"
            "}\n"
            "\n"
            "def _detector(which='x^5', reveal=False):\n"
            "    p = _PRESETS[which]\n"
            "    # Keep windows where each function is well-behaved on screen.\n"
            "    hw = 1.6 if which == '(x^2 + 1)^7' else 3.0\n"
            "    xs = np.linspace(-hw, hw, 600)\n"
            "    fig, ax = plt.subplots()\n"
            "    ax.plot(xs, p['f'](xs), color=BLUE, lw=2.4, label=r'$f$')\n"
            "    ax.plot(xs, p['df'](xs), color=RED, lw=2.0, ls='--',\n"
            "            label=r\"$f'$\")\n"
            "    ax.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax.set_xlim(-hw, hw)\n"
            "    ax.set_xlabel('$x$'); ax.set_ylabel('$y$')\n"
            "    ax.set_title(f'$f(x) = $ {which}', color=DARK)\n"
            "    ax.legend(loc='upper left', framealpha=0.9)\n"
            "    plt.show()\n"
            "    if reveal:\n"
            "        display(Markdown(f\"**Rule:** {p['rule']}\"))\n"
            "        display(Markdown(p['work']))\n"
            "        display(Markdown(f\"*{p['note']}*\"))\n"
            "    else:\n"
            "        display(Markdown('*Tick **reveal** to name the rule and '\n"
            "                         'see the worked derivative.*'))\n"
            "\n"
            "interact(_detector,\n"
            "         which=Dropdown(options=list(_PRESETS), value='x^5',\n"
            "                        description='function'),\n"
            "         reveal=Checkbox(value=False, description='reveal answer'));\n"
        ),

        # ---------------------------------------------------------------
        # Widget 2 — Product-rule area animation
        # ---------------------------------------------------------------
        nbb.md(
            "## 2. Why the product rule has *two* terms\n\n"
            "The naive guess $(fg)' = f'g'$ is wrong, and a growing rectangle "
            "shows exactly what it misses. Let the width be $f(t)=1+t$ and the "
            "height be $g(t)=1+0.6t$, so the **area** is the product "
            "$A(t)=f(t)\\,g(t)$. Watch the rectangle grow as $t$ advances.\n\n"
            "Each frame the area gains three pieces: a **blue** strip from the "
            "extra width ($f'\\,g$), a **green** strip from the extra height "
            "($f\\,g'$), and a tiny **red** corner where both grew at once "
            "($f'g'\\,\\Delta t$). As the step shrinks that corner vanishes "
            "faster than the strips — which is precisely why\n\n"
            "$$\\frac{d}{dt}(fg) = f'\\,g + f\\,g'.$$\n\n"
            "Two strips survive; the corner does not."
        ),
        nbb.code(
            "f = lambda t: 1 + t          # width\n"
            "g = lambda t: 1 + 0.6*t      # height\n"
            "fp, gp = 1.0, 0.6            # f'(t), g'(t) are constant here\n"
            "\n"
            "fig, ax = plt.subplots()\n"
            "_T = np.linspace(0.0, 2.0, 48)   # one t per frame\n"
            "_dt = 0.55                       # visible growth step per frame\n"
            "\n"
            "def _frame(i):\n"
            "    ax.clear()\n"
            "    t = _T[i]\n"
            "    w, h = f(t), g(t)\n"
            "    dw, dh = fp*_dt, gp*_dt\n"
            "    # Base rectangle: the current area f(t) g(t).\n"
            "    ax.add_patch(plt.Rectangle((0, 0), w, h, facecolor=LIGHT,\n"
            "                 edgecolor=DARK, lw=1.5, zorder=1))\n"
            "    ax.text(w/2, h/2, r'$f\\,g$', ha='center', va='center',\n"
            "            color=DARK, fontsize=14)\n"
            "    # Strip from extra width: f' g.\n"
            "    ax.add_patch(plt.Rectangle((w, 0), dw, h, facecolor=SHADE,\n"
            "                 edgecolor=BLUE, lw=1.2, alpha=0.85, zorder=2))\n"
            "    ax.text(w + dw/2, h/2, r\"$f'g$\", ha='center', va='center',\n"
            "            color=BLUE, fontsize=12, rotation=90)\n"
            "    # Strip from extra height: f g'.\n"
            "    ax.add_patch(plt.Rectangle((0, h), w, dh, facecolor=SHADEG,\n"
            "                 edgecolor=GREEN, lw=1.2, alpha=0.85, zorder=2))\n"
            "    ax.text(w/2, h + dh/2, r\"$fg'$\", ha='center', va='center',\n"
            "            color=GREEN, fontsize=12)\n"
            "    # The vanishing corner: f' g' (dt)^2.\n"
            "    ax.add_patch(plt.Rectangle((w, h), dw, dh, facecolor=SHADE2,\n"
            "                 edgecolor=RED, lw=1.2, zorder=3))\n"
            "    ax.annotate(r\"$f'g'$ (vanishes)\", xy=(w + dw/2, h + dh/2),\n"
            "                xytext=(w + dw/2 + 0.35, h + dh/2 + 0.7),\n"
            "                color=RED, fontsize=11,\n"
            "                arrowprops=dict(arrowstyle='->', color=RED))\n"
            "    ax.set_xlim(0, 5.0); ax.set_ylim(0, 4.0)\n"
            "    ax.set_aspect('equal')\n"
            "    ax.set_xlabel(r'width $f(t)=1+t$')\n"
            "    ax.set_ylabel(r'height $g(t)=1+0.6t$')\n"
            "    ax.set_title(f'$t = {t:.2f}$:   area $f g = {w*h:.2f}$',\n"
            "                 color=DARK)\n"
            "\n"
            "ani = animation.FuncAnimation(fig, _frame, frames=48, interval=90)\n"
            "plt.close(fig)\n"
            "HTML(ani.to_jshtml())\n"
        ),

        # ---------------------------------------------------------------
        # Widget 3 — Build a derivative (chain rule)
        # ---------------------------------------------------------------
        nbb.md(
            "## 3. Build a derivative (the chain rule)\n\n"
            "Most real functions are **compositions** — an *outer* function "
            "wrapped around an *inner* one, $f(g(x))$. Pick an outer and an "
            "inner from the dropdowns; the notebook forms the composition "
            "$f(g(x))$ and assembles its derivative the way the chain rule "
            "tells you to:\n\n"
            "$$\\frac{d}{dx}\\,f(g(x)) = \\underbrace{f'(g(x))}_{\\text{outer}'"
            "\\text{ at the inside}}\\cdot\\;\\underbrace{g'(x)}_{\\text{inside}'}.$$\n\n"
            "Differentiate the outer, **leave the inside alone**, then multiply "
            "by the derivative of the inside. The blue curve is the composition "
            "$f(g(x))$; the red dashed curve is the derivative the rule "
            "produced — so you can confirm the assembled factors are right."
        ),
        nbb.code(
            "# Outer functions: f, f', and a LaTeX template g(.) -> f(.) and f'(.).\n"
            "_OUTER = {\n"
            "    'sin':   dict(f=np.sin, df=np.cos,\n"
            "                  f_tex=lambda u: rf'\\sin\\!\\left({u}\\right)',\n"
            "                  df_tex=lambda u: rf'\\cos\\!\\left({u}\\right)'),\n"
            "    'exp':   dict(f=np.exp, df=np.exp,\n"
            "                  f_tex=lambda u: rf'e^{{{u}}}',\n"
            "                  df_tex=lambda u: rf'e^{{{u}}}'),\n"
            "    '(.)^3': dict(f=lambda u: u**3, df=lambda u: 3*u**2,\n"
            "                  f_tex=lambda u: rf'\\left({u}\\right)^3',\n"
            "                  df_tex=lambda u: rf'3\\left({u}\\right)^2'),\n"
            "    'sqrt':  dict(f=np.sqrt, df=lambda u: 0.5/np.sqrt(u),\n"
            "                  f_tex=lambda u: rf'\\sqrt{{{u}}}',\n"
            "                  df_tex=lambda u: rf'\\frac{{1}}{{2\\sqrt{{{u}}}}}'),\n"
            "}\n"
            "# Inner functions: g, g', a LaTeX string, and a domain that keeps\n"
            "# sqrt's argument >= 0 so every composition is real on screen.\n"
            "_INNER = {\n"
            "    'x^2':    dict(g=lambda x: x**2, dg=lambda x: 2*x,\n"
            "                   tex='x^2', dtex='2x', dom=(-2.2, 2.2)),\n"
            "    '3x + 1': dict(g=lambda x: 3*x + 1, dg=lambda x: 3 + 0*x,\n"
            "                   tex='3x+1', dtex='3', dom=(0.0, 2.0)),\n"
            "    'x^2 + 1':dict(g=lambda x: x**2 + 1, dg=lambda x: 2*x,\n"
            "                   tex='x^2+1', dtex='2x', dom=(-2.2, 2.2)),\n"
            "}\n"
            "\n"
            "def _build(outer='sin', inner='x^2'):\n"
            "    o, n = _OUTER[outer], _INNER[inner]\n"
            "    a, b = n['dom']\n"
            "    xs = np.linspace(a, b, 600)\n"
            "    gx = n['g'](xs)\n"
            "    comp = o['f'](gx)                       # f(g(x))\n"
            "    deriv = o['df'](gx) * n['dg'](xs)       # f'(g(x)) * g'(x)\n"
            "\n"
            "    fig, ax = plt.subplots()\n"
            "    ax.plot(xs, comp, color=BLUE, lw=2.4, label=r'$f(g(x))$')\n"
            "    ax.plot(xs, deriv, color=RED, lw=2.0, ls='--',\n"
            "            label=r\"$f'(g(x))\\,g'(x)$\")\n"
            "    ax.axhline(0, color=GRAY, lw=0.8)\n"
            "    ax.set_xlim(a, b)\n"
            "    ax.set_xlabel('$x$'); ax.set_ylabel('$y$')\n"
            "    ax.set_title('Composition and its chain-rule derivative',\n"
            "                 color=DARK)\n"
            "    ax.legend(loc='upper left', framealpha=0.9)\n"
            "    plt.show()\n"
            "\n"
            "    # Assemble the answer factor by factor.\n"
            "    f_of_g = o['f_tex'](n['tex'])\n"
            "    outer_prime = o['df_tex'](n['tex'])\n"
            "    display(Markdown(rf\"**Composition:**  $f(g(x)) = {f_of_g}$\"))\n"
            "    display(Markdown(\n"
            "        r'**Chain rule:** $\\;\\dfrac{d}{dx}f(g(x))'\n"
            "        rf'= \\underbrace{{{outer_prime}}}_{{\\text{{outer}}\\,'\n"
            "        rf\"' \\text{{ at the inside}}}}\"\n"
            "        rf'\\;\\cdot\\;\\underbrace{{{n[\"dtex\"]}}}'\n"
            "        r\"_{\\text{inside}\\,'}$\"))\n"
            "\n"
            "interact(_build,\n"
            "         outer=Dropdown(options=list(_OUTER), value='sin',\n"
            "                        description='outer  $f$'),\n"
            "         inner=Dropdown(options=list(_INNER), value='x^2',\n"
            "                        description='inner  $g$'));\n"
        ),

        nbb.md(
            "---\n\n"
            "*Five rules — power, sum, product, quotient, chain — and you can "
            "now differentiate almost anything in seconds, never returning to a "
            "difference quotient. The chain rule is the one to keep closest: in "
            "Chapter 9 it becomes the engine of gradient descent, and run "
            "**backward** across a deep composition it is the backpropagation "
            "that trains every neural network.*"
        ),
    ]
    nbb.build("ch4_rules.ipynb", cells)


if __name__ == "__main__":
    build()
